{{- $environment := .Values.environment | default dict }}
{{- if and (.Values.enabled) (.Values.canary.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crabserver-canary
  labels:
    app: crabserver-canary
  namespace: crab
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.canary.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: crabserver
  template:
    metadata:
      annotations:
        {{- $base := dict "configHash" (include "crabserver.configHash" .) -}}
        {{- $merged := merge $base (.Values.podAnnotations | default dict) -}}
        {{- toYaml $merged | nindent 8 }}
      labels:
        app: crabserver
        env: k8s-{{.Values.environment}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: crabserver
          image: "{{ .Values.canary.image.path }}:{{ .Values.canary.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.canary.image.pullPolicy }}
          securityContext:
           {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
          - containerPort: 8270
            protocol: TCP
            name: crabserver
          - containerPort: 18270
            protocol: TCP
            name: crabserver-mon
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.canary.image.command }}
          command:
          {{- toYaml .Values.canary.image.command | nindent 10 }}
          {{- end }}
          {{- if .Values.canary.image.args }}
          args:
          {{- toYaml .Values.canary.image.args | nindent 10 }}
          {{- end }}
          env:
          {{- toYaml .Values.canary.image.env | nindent 10 }}
          livenessProbe:
          {{- if eq (toString $environment) "prod" }}
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- else if eq (toString $environment) "preprod" }}
          {{- toYaml .Values.livenessProbePreProd | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.livenessProbeTest | nindent 12 }}
          {{- end }}
          readinessProbe:
          {{- if eq (toString $environment) "prod" }}
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- else if eq (toString $environment) "preprod" }}
          {{- toYaml .Values.readinessProbePreProd | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.readinessProbeTest | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: proxy-secrets
            mountPath: /etc/proxy
            readOnly: true
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
          - name: robot-secrets
            mountPath: /etc/robots
            readOnly: true
          - name: hmac-secrets
            mountPath: /etc/hmac
            readOnly: true
          - mountPath: /host/etc/grid-security
            name: etc-grid-security
            readOnly: true
          - name: config
            mountPath: /opt/config
          - name: token-secrets
            mountPath: /etc/token
            readOnly: true
          securityContext:
            privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: crabserver-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: config
        configMap:
          name: crabserver
      - name: token-secrets
        secret:
          secretName: token-secrets
{{- end }}
