  apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: cron-spider-affiliation
    namespace: spider
  spec:
    schedule: "17 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: spider-account
            containers:
            - name: cms-htcondor-es
              image: mrceyhun/cms_htcondor_es:latest
              args:
              - /bin/sh
              - -c
              - echo "run k8s_affiliation_cache.sh"; /cms-htcondor-es/k8s_affiliation_cache.sh $AFFILIATION_DIR_LOCATION; echo "ls -al /etc/affiliations"; ls -al $AFFILIATION_DIR_LOCATION
              env:
                - name: AFFILIATION_DIR_LOCATION
                  value: /cms_shared/affiliation_dir.json
                - name: CELERY_BROKER_URL
                  value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/0
                - name: CELERY_RESULT_BACKEND
                  value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/1
                - name: CELERY_TEST
                  value: '"false"'
                - name: C_FORCE_ROOT
                  value: '"true"'
                - name: PYTHONPATH
                  value: /cms-htcondor-es/src:$PYTHONPATH
                - name: REQUESTS_CA_BUNDLE # provided in Dockerfile too. Certs path for ES and AMQ connections
                  value: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
              lifecycle:
                postStart:
                  exec:
                    command:
                    - bash
                    - -c
                    - sudo chmod 0777 $AFFILIATION_DIR_LOCATION; sudo chown 1414:1414 $AFFILIATION_DIR_LOCATION; ls -al $AFFILIATION_DIR_LOCATION
              stdin: true
              tty: true
              volumeMounts:
                - name: spider-shared-ceph-claim
                  mountPath: /cms_shared
            restartPolicy: Never
            securityContext:
              fsGroup: 1414
            volumes:
              - name: spider-shared-ceph-claim
                persistentVolumeClaim:
                  claimName: spider-ceph-claim
                  readOnly: false
