apiVersion: batch/v1
kind: CronJob
metadata:
  name: crab-popularity
  namespace: hdfs
  labels:
    app: crab-popularity
spec:
  schedule: "00 22 05 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crab-popularity
        spec:
          restartPolicy: Never
          containers:
          - name: crab-popularity
            image: registry.cern.ch/cmsmonitoring/crab-popularity:test
            imagePullPolicy: Always
            command: ["/bin/bash", "/opt/spark-apps/crab-popularity/cron4crab_popularity.sh"]
            args:
              - "--keytab"
              - "/etc/secrets/keytab"
              - "--output"
              - "/eos/user/c/cmsmonit/www/crabPop_cron/data"
              - "--p1"
              - "32606"
              - "--p2"
              - "32607"
              - "--host"
              - "$(MY_NODE_NAME)"
              - "--wdir"
              - "/opt/spark-apps/crab-popularity"
            ports:
            - containerPort: 32606
              hostPort: 32606
              protocol: TCP
            - containerPort: 32607
              hostPort: 32607
              protocol: TCP
            env:
            - name: K8S_ENV
              value: prod
            - name: HOSTNAME
              value: crab-popularity
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PUSHGATEWAY_URL
              value: pushgateway.default.svc.cluster.local:9091
            volumeMounts:
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: cron-spark-jobs-secrets
              mountPath: /etc/secrets
              readOnly: true
            resources:
              limits:
                cpu: "2"
                memory: 6Gi
              requests:
                cpu: 100m
                memory: 100Mi
          volumes:
          - name: eos
            hostPath:
              path: /var/eos
          - name: cron-spark-jobs-secrets
            secret:
              secretName: cron-spark-jobs-secrets
              defaultMode: 420

