apiVersion: batch/v1
kind: CronJob
metadata:
  name: hpc-usage
  namespace: hdfs
  labels:
    app: hpc-usage
spec:
  schedule: "10 02 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hpc-usage
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: hpc-usage-secrets
            secret:
              secretName: hpc-usage-secrets
              defaultMode: 420
          - name: eos
            hostPath:
              path: /var/eos
          containers:
          - name: hpc-usage
            image: registry.cern.ch/cmsmonitoring/hpc-usage:test
            imagePullPolicy: Always
            command: ["/bin/bash", "/opt/spark-apps/hpc-usage/cron4hpc_usage.sh"]
            args:
              - "--keytab"
              - "/etc/secrets/keytab"
              - "--output"
              - "/eos/user/c/cmsmonit/www/hpc_usage_cron"
              - "--url"
              - "https://cmsdatapop.web.cern.ch/cmsdatapop/hpc_usage"
              - "--iterative"
              - "--p1"
              - "32614"
              - "--p2"
              - "32615"
              - "--host"
              - "$(MY_NODE_NAME)"
              - "--wdir"
              - "/data"
            ports:
            - containerPort: 32614
              hostPort: 32614
              protocol: TCP
            - containerPort: 32615
              hostPort: 32615
              protocol: TCP
            env:
            - name: K8S_ENV
              value: prod
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PUSHGATEWAY_URL
              value: pushgateway.default.svc.cluster.local:9091
            volumeMounts:
            - name: eos
              mountPath: /eos
            - name: hpc-usage-secrets
              mountPath: /etc/secrets
              readOnly: true
            resources:
              limits:
                cpu: "2"
                memory: 6Gi
              requests:
                cpu: 100m
                memory: 100Mi
          terminationGracePeriodSeconds: 30
