apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-spider-affiliation
spec:
  schedule: "14 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spider-account
          containers:
          - name: cms-htcondor-es
            image: veknet/cms-htcondor-es
            args:
            - /bin/sh
            - -c
            - echo "run k8s_affiliation_cache.sh"; /cms-htcondor-es/k8s_affiliation_cache.sh /etc/affiliations/affiliation.json; echo "ls -al /etc/affiliations"; ls -al /etc/affiliations
            tty: true
            stdin: true
            lifecycle:
              postStart:
                exec:
                  command:
                  - bash
                  - -c
                  - sudo chmod 0777 /etc/affiliations; sudo chown spider:spider /etc/affiliations; ls -al /etc/affliations
            volumeMounts:
            - name: spider-secrets
              mountPath: /etc/spider
              readOnly: true
            - name: affiliations-volume
              mountPath: /etc/affiliations
          restartPolicy: Never
          volumes:
          - name: spider-secrets
            secret:
              secretName: spider-secrets
          - name: affiliations-volume
            persistentVolumeClaim:
              claimName: affilations-cephfs-claim
