apiVersion: batch/v1
kind: CronJob
metadata:
  name: wma-agent-count
  namespace: hdfs
  labels:
    app: wma-agent-count
spec:
  schedule: "00 10 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: wma-agent-count
        spec:
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes:
          - name: cron-spark-jobs-secrets
            secret:
              secretName: cron-spark-jobs-secrets
              defaultMode: 420
          - name: eos
            hostPath:
              path: /var/eos
          containers:
          - name: wma-agent-count
            image: registry.cern.ch/cmsmonitoring/wma-agent-count:test
            ports:
            - containerPort: 32616
              hostPort: 32616
              protocol: TCP
            - containerPort: 32617
              hostPort: 32617
              protocol: TCP
            env:
            - name: K8S_ENV
              value: prod
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PUSHGATEWAY_URL
              value: pushgateway.default.svc.cluster.local:9091
            volumeMounts:
            - name: eos
              mountPath: /eos
            - name: cron-spark-jobs-secrets
              mountPath: /etc/secrets
              readOnly: true
            imagePullPolicy: Always
            command: ["/bin/bash", "/opt/spark-apps/wma-agent-count/cron4wma_agent_count.sh"]
            args:
              - "--keytab"
              - "/etc/secrets/keytab"
              - "--conf"
              - " /etc/secrets/test_tenant_secret"
              - "--p1"
              - "32616"
              - "--p2"
              - "32617"
              - "--host"
              - "$(MY_NODE_NAME)"
              - "--wdir"
              - "/data"
            resources:
              limits:
                cpu: "2"
                memory: 6Gi
              requests:
                cpu: 100m
                memory: 100Mi
