kind: Service
apiVersion: v1
metadata:
  name: sitedb
spec:
  selector:
    app: sitedb
  ports:
    - port: 8051
      targetPort: 8051
      name: sitedb
    - port: 18051
      targetPort: 18051
      name: sitedb-mon
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: sitedb
  name: sitedb
spec:
  selector:
    matchLabels:
      app: sitedb
  replicas: 1
  template:
    metadata:
      labels:
        app: sitedb
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: veknet/sitedb
        name: sitedb
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 20 && /data/monitor.sh"]
        ports:
        - containerPort: 8051
          protocol: TCP
          name: sitedb
        - containerPort: 18051
          protocol: TCP
          name: sitedb-mon
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
      volumes:
      - name: secrets
        secret:
          secretName: sitedb-secrets
          # https://github.com/kubernetes/kubernetes/issues/34982
          defaultMode: 256
          items:
            - key: "robotcert.pem"
              path: "robotcert.pem"
              mode: 0640
            - key: "robotkey.pem"
              path: "robotkey.pem"
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
