apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-token-reviewer
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "serviceaccounts/token", "secrets", "pods"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-token-reviewer-binding
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: vault-secrets-operator
roleRef:
  kind: ClusterRole
  name: vault-token-reviewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  annotations:
    kubernetes.io/service-account.name: vault-auth
    kubernetes.io/service-account.namespace: default
type: kubernetes.io/service-account-token
immutable: true
