apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-crab
  namespace: crab
  annotations:
    kubernetes.io/ingress.class: nginx
    # restrict access to this ingress controller from specific IPs
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range
    nginx.ingress.kubernetes.io/whitelist-source-range: 137.138.31.19,137.138.158.91,137.138.33.200,137.138.54.48
spec:
  rules:
  - host: cmsweb-srv.cern.ch
    http:
      paths:
      - path: /crabserver
        backend:
          serviceName: crabserver
          servicePort: 8270
      - path: /crabcache
        backend:
          serviceName: crabcache
          servicePort: 8271
