apiVersion: v1
entries:
  crabcache:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.177620418+02:00"
    description: A Helm chart for Kubernetes
    digest: ea9696ce22d094affffee3f2a36d781c1340814219fa53057a2d4062f12f9f44
    name: crabcache
    type: application
    urls:
    - crabcache-0.1.0.tgz
    version: 0.1.0
  crabserver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.178909476+02:00"
    description: A Helm chart for Kubernetes
    digest: 22f91c90b8bd1476f5f83e33b2e3bc528b32687f799acb187dcaf8de8c1f1d45
    name: crabserver
    type: application
    urls:
    - crabserver-0.1.0.tgz
    version: 0.1.0
  das-mongo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.179687996+02:00"
    description: A Helm chart for Kubernetes
    digest: d5b125457e7c64a98e7c4b2617d44b89ca2a4d425964c4a48ea15b770d268088
    name: das-mongo
    type: application
    urls:
    - das-mongo-0.1.0.tgz
    version: 0.1.0
  das-mongo-exporter:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.180636291+02:00"
    description: A Helm chart for Kubernetes
    digest: f6394a2ea0a66c53cf2037047bd2e8308a98db397da7a8696183199ae2ba6048
    name: das-mongo-exporter
    type: application
    urls:
    - das-mongo-exporter-0.1.0.tgz
    version: 0.1.0
  das-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.181821284+02:00"
    description: A Helm chart for Kubernetes
    digest: bc5a24f41c72ee1b3554abe5268f8882be83f1c461b61b4154936e4f241f3add
    name: das-server
    type: application
    urls:
    - das-server-0.1.0.tgz
    version: 0.1.0
  dbs-global-r:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.183015778+02:00"
    description: A Helm chart for Kubernetes
    digest: 8bb2e41e95eafc5739f5c9eeaa41d20ce5ef35b3726a50def5e83714dd21cbda
    name: dbs-global-r
    type: application
    urls:
    - dbs-global-r-0.1.0.tgz
    version: 0.1.0
  dbs-global-w:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.184060404+02:00"
    description: A Helm chart for Kubernetes
    digest: 91b078680e29955d17b7320a41f04446a715905f8a81bde078ddbd162032f5ea
    name: dbs-global-w
    type: application
    urls:
    - dbs-global-w-0.1.0.tgz
    version: 0.1.0
  dbs-migrate:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.185176807+02:00"
    description: A Helm chart for Kubernetes
    digest: 5f7e05ef524a3b8f59d9a6e35e3f5271e013eb7d093388ffa0fb982a5af2cad8
    name: dbs-migrate
    type: application
    urls:
    - dbs-migrate-0.1.0.tgz
    version: 0.1.0
  dbs-phys03-r:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.186312601+02:00"
    description: A Helm chart for Kubernetes
    digest: 47fbc26c3654dbeb21c3bc48cb8059bd6057dae65ada39e38213f7a7bcafbf5e
    name: dbs-phys03-r
    type: application
    urls:
    - dbs-phys03-r-0.1.0.tgz
    version: 0.1.0
  dbs-phys03-w:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.187394451+02:00"
    description: A Helm chart for Kubernetes
    digest: 448c06a7958462fcc2d6dff980d5c215d140cb1e1f41ffc16f287c00bc4f61e1
    name: dbs-phys03-w
    type: application
    urls:
    - dbs-phys03-w-0.1.0.tgz
    version: 0.1.0
  dbs2go:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.188384956+02:00"
    description: A Helm chart for Kubernetes
    digest: 5d288fe48d2152ff124775454dcb559844af1a123d4aeea092ef78db7ee3952d
    name: dbs2go
    type: application
    urls:
    - dbs2go-0.1.0.tgz
    version: 0.1.0
  dbsmigration:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.189425108+02:00"
    description: A Helm chart for Kubernetes
    digest: e660786470ecf022e60928fcd16f891d87585979063c4dab30e2cab8a3052ef2
    name: dbsmigration
    type: application
    urls:
    - dbsmigration-0.1.0.tgz
    version: 0.1.0
  exitcodes:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.191092253+02:00"
    description: A Helm chart for Exitcodes
    digest: 43a8efc6930cd566cb23da294a07fb1bad8135f7c13c861aaefbf6e5ea3fc91b
    name: exitcodes
    type: application
    urls:
    - exitcodes-0.1.0.tgz
    version: 0.1.0
  httpgo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.191824919+02:00"
    description: A Helm chart for HTTPGO service
    digest: fa30b10cf8c57e826aa570fc8f67021ea83604a05d634342a9adb424f3276a08
    name: httpgo
    type: application
    urls:
    - httpgo-0.1.0.tgz
    version: 0.1.0
  ms-output-mongo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.192649514+02:00"
    description: A Helm chart for Kubernetes
    digest: 18cc14c5caa5e9a58f495aad9d2faaf5a943d97a9e9b013a5e60179cb1e19e2e
    name: ms-output-mongo
    type: application
    urls:
    - ms-output-mongo-0.1.0.tgz
    version: 0.1.0
  reqmgr2:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.202711699+02:00"
    description: A Helm chart for Kubernetes
    digest: 3180b221280bfd1eb3be194ca3d02618d795954a8b09a47edd4906f41f39eca1
    name: reqmgr2
    type: application
    urls:
    - reqmgr2-0.1.0.tgz
    version: 0.1.0
  reqmgr2-tasks:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.203703517+02:00"
    description: A Helm chart for Kubernetes
    digest: 2dede6303a4707c0e223315f081c5262f749099215514367ab5baa3f4bc2da9f
    name: reqmgr2-tasks
    type: application
    urls:
    - reqmgr2-tasks-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-monitor:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.204932874+02:00"
    description: A Helm chart for Kubernetes
    digest: 8af02c59b033361c2bbda893c5aecbaca9c08d94aa512f56bb24822aefbd9bc7
    name: reqmgr2ms-monitor
    type: application
    urls:
    - reqmgr2ms-monitor-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-output:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.205964243+02:00"
    description: A Helm chart for Kubernetes
    digest: c29eb3a8dffb5703d9e809263ad1c913ac020050386211df9bd857874a99f397
    name: reqmgr2ms-output
    type: application
    urls:
    - reqmgr2ms-output-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-rulecleaner:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.207087263+02:00"
    description: A Helm chart for Kubernetes
    digest: 86e98f654cf36626d4f0baf86f7d158f81a07313f3fd9c0d751e2d2b0abd9daf
    name: reqmgr2ms-rulecleaner
    type: application
    urls:
    - reqmgr2ms-rulecleaner-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-transferor:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.208302533+02:00"
    description: A Helm chart for Kubernetes
    digest: ab415c49f6165436e2b04d92afbcc76962e69ea914c97d7c878e3be74cd3df39
    name: reqmgr2ms-transferor
    type: application
    urls:
    - reqmgr2ms-transferor-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-unmerged-t1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.209313178+02:00"
    description: A Helm chart for Kubernetes
    digest: dfb9875327d5d36bb701610fc0eed6e0bc5c19506cce56a7987ce7d0554689f3
    name: reqmgr2ms-unmerged-t1
    type: application
    urls:
    - reqmgr2ms-unmerged-t1-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-unmerged-t2t3:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.210350836+02:00"
    description: A Helm chart for Kubernetes
    digest: 2a5091b54aa733c772ff8cac695285c94a0d6c8ac1ca61c857cb0cfb5bd95807
    name: reqmgr2ms-unmerged-t2t3
    type: application
    urls:
    - reqmgr2ms-unmerged-t2t3-0.1.0.tgz
    version: 0.1.0
  reqmgr2ms-unmerged-t2t3us:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.211480223+02:00"
    description: A Helm chart for Kubernetes
    digest: a067ab095938b9cce33e24d0fe5f47701fb1fed1e09a073cae5327ddf75160aa
    name: reqmgr2ms-unmerged-t2t3us
    type: application
    urls:
    - reqmgr2ms-unmerged-t2t3us-0.1.0.tgz
    version: 0.1.0
  reqmon:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.212744756+02:00"
    description: A Helm chart for Kubernetes
    digest: eff1a176ab5d0ce4aa380eda14041cc1703d468f77d2ef541e1d1e34fa303eb5
    name: reqmon
    type: application
    urls:
    - reqmon-0.1.0.tgz
    version: 0.1.0
  reqmon-tasks:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.213740917+02:00"
    description: A Helm chart for Kubernetes
    digest: 01c375e2870ef7c4c2557ec11f083e7178eaac99fd0e5f5bdfbd59f141e97ee0
    name: reqmon-tasks
    type: application
    urls:
    - reqmon-tasks-0.1.0.tgz
    version: 0.1.0
  t0reqmon:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.214693257+02:00"
    description: A Helm chart for Kubernetes
    digest: b21435350c0f0efdc0e216c81cad4b6beeaf3a80df7bfe1162f8b2458abaf8d8
    name: t0reqmon
    type: application
    urls:
    - t0reqmon-0.1.0.tgz
    version: 0.1.0
  t0reqmon-tasks:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.215805852+02:00"
    description: A Helm chart for Kubernetes
    digest: c52101524755286a79fa2bfe64f67fa307d270da6c4988106c3f7859f5718c88
    name: t0reqmon-tasks
    type: application
    urls:
    - t0reqmon-tasks-0.1.0.tgz
    version: 0.1.0
  t0wmadatasvc:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.216744349+02:00"
    description: A Helm chart for Kubernetes
    digest: 004b93105e8556ccba731afa361696dc4ce39ae36ba23e93a261dc79594f8677
    name: t0wmadatasvc
    type: application
    urls:
    - t0wmadatasvc-0.1.0.tgz
    version: 0.1.0
  wmarchive:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.217635638+02:00"
    description: A Helm chart for Kubernetes
    digest: 2e83785ec7b0cb2198010478838ff1d60f41ec0e30ade805ed7a945477b42b64
    name: wmarchive
    type: application
    urls:
    - wmarchive-0.1.0.tgz
    version: 0.1.0
  workqueue:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-30T11:32:42.218955754+02:00"
    description: A Helm chart for Kubernetes
    digest: a766c1d7b066314d7d3eb843276e11d52246f58ea7563629b07e8661559824a7
    name: workqueue
    type: application
    urls:
    - workqueue-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-30T11:32:42.172961905+02:00"
