---
# Source: kube-eagle/templates/serviceaccount.yaml 
apiVersion: v1        
kind: ServiceAccount
metadata:       
  labels:  
    app: kube-eagle
  name: sa-kube-eagle                         
  namespace: monitoring
---                     
# Source: kube-eagle/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:          
  labels:                  
    app: kube-eagle      
  name: kube-eagle
  namespace: monitoring
rules:          
  - apiGroups:       
      - ""                 
    resources:
      - nodes
      - pods      
    verbs:                          
      - get                       
      - list                          
  - apiGroups:
      - metrics.k8s.io 
    resources:               
      - pods
      - nodes                          
    verbs:       
      - get               
      - list                                                  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding          
metadata:                  
  labels:                            
    app: kube-eagle         
  name: kube-eagle
subjects:                        
  - kind: ServiceAccount   
    name: sa-kube-eagle
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eagle
---
# Source: kube-eagle/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-eagle
  namespace: monitoring
  labels:
    app: kube-eagle
spec:
  type: ClusterIP
#   type: NodePort
  ports:
    - port: 8080
      targetPort: http
#       nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: kube-eagle
    release: release-name
---
# Source: kube-eagle/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-eagle
  namespace: monitoring
  labels:
    app: kube-eagle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eagle
      release: release-name
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: kube-eagle
        release: release-name
    spec:
      serviceAccountName: sa-kube-eagle
      containers:
        - name: kube-eagle
          image: "quay.io/google-cloud-tools/kube-eagle:1.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: TELEMETRY_HOST
              value: "0.0.0.0"
            - name: TELEMETRY_PORT
              value: "8080"
            - name: METRICS_NAMESPACE
              value: "eagle"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 5
            httpGet:
              path: /health
              port: http
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              path: /health
              port: http
          resources:
            {}
---
