apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: cms-monitoring.cern.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy-server
          servicePort: 443
  tls:
  - hosts:
    - cms-monitoring.cern.ch
  secretName: auth-secrets
