apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-1h
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-cert"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-key"
          containers:
            - name: {{ .Release.Name }}-1h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
              command: ['/root/CMSRucio/docker/CMSRucioClient/scripts/k8s_sync_sites.sh']
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-12h
spec:
  schedule: "10 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-cert"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-key"
          containers:
            - name: {{ .Release.Name }}-12h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
              command: ['/root/CMSRucio/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh']
          restartPolicy: OnFailure
