apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio-cron-jobs.fullname" . }}.cfg
  labels:
    app: {{ template "rucio-cron-jobs.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key1, $val1 := .Values.config }}
  {{- range $key2, $val2 := $val1}}
  {{ $key1 | lower }}_{{ $key2 }}: {{ $val2 | b64enc | quote}}
  {{- end}}
  {{- end}}
