kind: Service
apiVersion: v1
metadata:
  name: rr-prod-fe
  namespace: runregistry
spec:
  selector:
    app: rr-prod-fe
  ports:
    - port: 8350
      targetPort: 7001
      name: rr-prod-fe
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-prod-fe
  name: rr-prod-fe
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-prod-fe
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-prod-fe
    spec:
      containers:
        - image: cmssw/runregistry-frontend
          name: rr-prod-fe
          tty: true
          stdin: true
          env:
            - name: NODE_ENV
              value: production
            - name: ENV
              value: production
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 7001
              protocol: TCP
              name: rr-prod-fe
---
kind: Service
apiVersion: v1
metadata:
  name: rr-prod-api
  namespace: runregistry
spec:
  selector:
    app: rr-prod-api
  ports:
    - port: 8351
      targetPort: 9500
      name: rr-prod-api
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-prod-api
  name: rr-prod-api
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-prod-api
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-prod-api
    spec:
      containers:
        - image: cmssw/runregistry-backend
          name: rr-prod-api
          tty: true # Not sure
          stdin: true # Not sure
          env:
            - name: NODE_ENV
              value: production
            - name: ENV
              value: prod_kubernetes
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 9500
              protocol: TCP
              name: rr-prod-api
---
kind: Service
apiVersion: v1
metadata:
  name: rr-prod-redis
  namespace: runregistry
spec:
  selector:
    app: rr-prod-redis
  ports:
    - port: 8353
      targetPort: 6379
      name: rr-prod-redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-prod-redis
  name: rr-prod-redis
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-prod-redis
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-prod-redis
    spec:
      containers:
        - image: redis:5.0.7-alpine
          name: rr-prod-redis
          tty: true # Not sure
          stdin: true # Not sure
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 6379
              protocol: TCP
              name: rr-prod-redis
---
# For development we have the same DEVELOPMENT

kind: Service
apiVersion: v1
metadata:
  name: rr-dev-fe
  namespace: runregistry
spec:
  selector:
    app: rr-dev-fe
  ports:
    - port: 8354
      targetPort: 7001
      name: rr-dev-fe
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-dev-fe
  name: rr-dev-fe
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-dev-fe
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-dev-fe
    spec:
      containers:
        - image: cmssw/runregistry-frontend
          name: rr-dev-fe
          tty: true # Not sure
          stdin: true # Not sure
          env:
            - name: NODE_ENV
              value: production
            - name: ENV
              value: staging
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 9600
              protocol: TCP
              name: rr-dev-fe
---
kind: Service
apiVersion: v1
metadata:
  name: rr-dev-api
  namespace: runregistry
spec:
  selector:
    app: rr-dev-api
  ports:
    - port: 8355
      targetPort: 9500
      name: rr-dev-api
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-dev-api
  name: rr-dev-api
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-dev-api
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-dev-api
    spec:
      containers:
        - image: cmssw/runregistry-backend
          name: rr-dev-api
          tty: true # Not sure
          stdin: true # Not sure
          env:
            - name: NODE_ENV
              value: production
            - name: ENV
              value: dev_kubernetes
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 9500
              protocol: TCP
              name: rr-dev-api
---
kind: Service
apiVersion: v1
metadata:
  name: rr-dev-redis
  namespace: runregistry
spec:
  selector:
    app: rr-dev-redis
  ports:
    - port: 8357
      targetPort: 6379
      name: rr-dev-redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rr-dev-redis
  name: rr-dev-redis
  namespace: runregistry
spec:
  selector:
    matchLabels:
      app: rr-dev-redis
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: rr-dev-redis
    spec:
      containers:
        - image: redis:5.0.7-alpine
          name: rr-dev-redis
          tty: true # Not sure
          stdin: true # Not sure
          resources:
            requests:
              memory: '256Mi'
              cpu: '10m'
            limits:
              memory: '3Gi'
              cpu: '1000m'
          ports:
            - containerPort: 6379
              protocol: TCP
              name: rr-dev-redis
