kind: Service
apiVersion: v1
metadata:
  name: cpueff-goweb
  namespace: cpueff
spec:
  selector:
    app: cpueff-goweb
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31380
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: cpueff-goweb
  name: cpueff-goweb
  namespace: cpueff
spec:
  selector:
    matchLabels:
      app: cpueff-goweb
  replicas: 1
  template:
    metadata:
      labels:
        app: cpueff-goweb
    spec:
      containers:
      - name: cpueff-goweb
        image: registry.cern.ch/cmsmonitoring/cpueff-goweb:cpueff-0.0.15
        # image: golang
        # command: [ "sleep" ]
        # args: [ "infinity" ]
        args:
          - /data/cpueff-goweb
          - -config
          - /data/config.json
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        - name: GIN_MODE
          value: release
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - name: cpueff-mongo-secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: cpueff-mongo-secrets
        secret:
          secretName: cpueff-mongo-secrets
          defaultMode: 0444
