apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbs2go-writer.fullname" . }}
  labels:
    {{- include "dbs2go-writer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port}}
    name: {{ .Values.service.name }}
    protocol: {{ .Values.service.protocol }}
  - port: {{ .Values.serviceMon.port }}
    protocol: {{ .Values.serviceMon.protocol }}
    name: {{ .Values.serviceMon.name }}
    targetPort: {{ .Values.serviceMon.port}}
  selector:
    {{- include "dbs2go-writer.selectorLabels" . | nindent 4 }}
