# traefik.toml
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
#     [entryPoints.https.tls]
#       [[entryPoints.https.tls.certificates]]
#       CertFile = "/ssl/server.crt"
#       KeyFile = "/ssl/server.key"

# Enable Kubernetes Ingress configuration backend.
# [kubernetes]
#     enablePassTLSCert = true
