kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: cmsmon-vol
  name: cmsmon-vol
spec:
   replicas: 1
   selector:
     matchLabels:
       app: cmsmon-vol
   template:
      metadata:
         labels:
           app: cmsmon-vol
      spec:
        securityContext:
          runAsUser: 1000
          #runAsGroup: 3000
          #fsGroup: 2000
        containers:
        - name: cmsmon-vol
          image: cmssw/cmsmon
          volumeMounts:
          - name: share-cinder-volume
            mountPath: /tmp/share
          - name: prom-cinder-volume
            mountPath: /tmp/prometheus
          - name: vm-cinder-volume
            mountPath: /tsdb
          securityContext:
            privileged: true
        volumes:
        - name: share-cinder-volume
          persistentVolumeClaim:
            claimName: share-volume-claim
        - name: prom-cinder-volume
          persistentVolumeClaim:
            claimName: prometheus-volume-claim
        - name: vm-cinder-volume
          persistentVolumeClaim:
            claimName: cinder-volume-claim
