kind: Service
apiVersion: v1
metadata:
  name: hpc-usage
  namespace: hdfs
spec:
  selector:
    app: hpc-usage
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port
      nodePort: 32600
      port: 32600
      protocol: TCP
      targetPort: 32600
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 32601
      port: 32601
      protocol: TCP
      targetPort: 32601
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hpc-usage
  namespace: hdfs
  labels:
    app: hpc-usage
data:
  run.sh: |
    #!/bin/bash
    . /etc/environment
    /bin/bash $WDIR/CMSSpark/bin/cron4hpc_usage.sh --keytab /etc/secrets/keytab \
      --output /eos/user/c/cmsmonit/www/hpc_usage \
      --url https://cmsdatapop.web.cern.ch/cmsdatapop/hpc_usage \
      --iterative \
      --p1 32600 --p2 32601 --host $MY_NODE_NAME --wdir $WDIR \
      >>/proc/$(cat /var/run/crond.pid)/fd/1 2>&1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hpc-usage
  namespace: hdfs
  labels:
    app: hpc-usage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-usage
  template:
    metadata:
      labels:
        app: hpc-usage
    spec:
      hostname: hpc-usage
      containers:
        - name: hpc-usage
          image: registry.cern.ch/cmsmonitoring/cmsmon-spark:v0.4.0.27
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: PUSHGATEWAY_URL
              value: "pushgateway.default.svc.cluster.local:9091"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    export > /etc/environment;
                    chmod +x /data/cronjob/run.sh;
                    echo "10 02 * * * /bin/bash /data/cronjob/run.sh" | crontab -;
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 32600
              name: port-0
            - containerPort: 32601
              name: port-1
          tty: true
          stdin: true
          volumeMounts:
            - name: hpc-usage-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: eos # EOS access
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: hpc-usage-configmap
              mountPath: /data/cronjob
      volumes:
        - name: hpc-usage-secrets
          secret:
            secretName: hpc-usage-secrets
        - name: eos
          hostPath:
            path: /var/eos
        - name: hpc-usage-configmap
          configMap:
            name: hpc-usage
