kind: Service
apiVersion: v1
metadata:
  name: condor-cpu-eff
  namespace: hdfs
spec:
  selector:
    app: condor-cpu-eff
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port
      nodePort: 31234
      port: 31234
      protocol: TCP
      targetPort: 31234
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31235
      port: 31235
      protocol: TCP
      targetPort: 31235
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: condor-cpu-eff
  namespace: hdfs
  labels:
    app: condor-cpu-eff
data:
  run.sh: |
    #!/bin/bash
    # Get env variables
    . /etc/environment
    # Condor cpu efficiency, last_n_days is 30
    # StepChain cpu efficiency, last_n_days is 15
    /bin/bash $WDIR/CMSSpark/bin/k8s_condor_cpu_efficiency.sh \
      $CMSMONIT_WWW 30 >>/proc/$(cat /var/run/crond.pid)/fd/1 2>&1
    /bin/bash $WDIR/CMSSpark/bin/k8s_stepchain_cpu_eff.sh \
      $CMSMONIT_WWW 15 >>/proc/$(cat /var/run/crond.pid)/fd/1 2>&1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: condor-cpu-eff
  namespace: hdfs
  labels:
    app: condor-cpu-eff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: condor-cpu-eff
  template:
    metadata:
      labels:
        app: condor-cpu-eff
    spec:
      hostname: condor-cpu-eff
      containers:
        - name: condor-cpu-eff
          image: registry.cern.ch/cmsmonitoring/cmsmon-spark:v0.0.0
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CMSMONIT_WWW # Define output path here
              value: /eos/user/c/cmsmonit/www
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    export > /etc/environment;
                    chmod +x /data/cronjob/run.sh;
                    echo "00 03 * * * /bin/bash /data/cronjob/run.sh" | crontab -;
          resources:
            limits:
              cpu: 2000m
              memory: 5Gi
            requests:
              cpu: 1000m
              memory: 750Mi
          ports:
            - containerPort: 31234 # spark.driver.port
              name: port-0
            - containerPort: 31235 # spark.driver.blockManager.port
              name: port-1
          tty: true
          stdin: true
          volumeMounts:
            - name: condor-cpu-eff-secrets
              mountPath: /etc/condor-cpu-eff
              readOnly: true
            - name: eos # EOS access
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: condor-cpu-eff-configmap
              mountPath: /data/cronjob
      volumes:
        - name: condor-cpu-eff-secrets
          secret:
            secretName: condor-cpu-eff-secrets
        - name: eos
          hostPath:
            path: /var/eos
        - name: condor-cpu-eff-configmap
          configMap:
            name: condor-cpu-eff
