kind: Service
apiVersion: v1
metadata:
  name: http-exporter-mss
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 18003
    protocol: TCP
    name: http
  selector:
    app: http-exporter-mss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-exporter-mss
  namespace: http
  labels:
     app: http-exporter-mss
spec:
   replicas: 1
   selector:
     matchLabels:
       app: http-exporter-mss
   template:
      metadata:
         labels:
           app: http-exporter-mss
      spec:
        containers:
        - args:
          - /data/http_exporter
          - -uri
          - "http://cmsmonitoring.web.cern.ch/cmsmonitoring/storageoverview/latest/StorageOverview.json"
          - -namespace
          - "mss"
          - -port
          - ":18003"
          - -agent
          - "monitoring"
          - -verbose
          name: http-exporter-mss
          image: registry.cern.ch/cmsmonitoring/http-exporter:20230321
          ports:
          - containerPort: 18003
