---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-sub-t2
  namespace: nats
  labels:
     app: nats-sub-t2
spec:
   replicas: 1
   selector:
     matchLabels:
       app: nats-sub-t2
   template:
      metadata:
         labels:
           app: nats-sub-t2
      spec:
        containers:
        - args:
          - /data/nats-sub
          - -rootCAs=/etc/nats/CERN_CA.crt,/etc/nats/CERN_CA1.crt
          - -t
          - -raw
          - -cmsAuth=/etc/nats/cms-auth
          - -vmUri=http://cms-monitoring.cern.ch:30422
          - "cms.wmarchive.site.T2.>"
          name: nats-sub
          image: registry.cern.ch/cmsmonitoring/nats-sub:go-0.5.44
          volumeMounts:
          - name: nats-secrets
            mountPath: /etc/nats
            readOnly: true
        volumes:
        - name: nats-secrets
          secret:
            secretName: nats-secrets
