---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-sub-stats
  namespace: nats
  labels:
     app: nats-sub-stats
spec:
   replicas: 1
   selector:
     matchLabels:
       app: nats-sub-stats
   template:
      metadata:
         labels:
           app: nats-sub-stats
      spec:
        containers:
        - args:
          - /data/nats-sub
          - -rootCAs=/etc/nats/CERN_CA.crt,/etc/nats/CERN_CA1.crt
          - -t
          - -cmsAuth=/etc/nats/cms-auth
          - -showStats
          - -statsBy=exitCode
          - -gatewayUri=http://cms-monitoring.cern.ch:30091
          - "cms.wmarchive.exitCode.>"
          name: nats-sub
          image: registry.cern.ch/cmsmonitoring/nats-sub:go-0.5.44
          volumeMounts:
          - name: nats-secrets
            mountPath: /etc/nats
            readOnly: true
        volumes:
        - name: nats-secrets
          secret:
            secretName: nats-secrets
