apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssb-alerts
  namespace: alerts
  labels:
     app: ssb-alerts
spec:
   replicas: 1
   selector:
     matchLabels:
       app: ssb-alerts
   template:
      metadata:
         labels:
           app: ssb-alerts
      spec:
        containers:
        - args:
          - /data/ssb_alert.sh
          - "select * from outages where time > now() - 2h"
          - "/etc/cmsmon-alerts/token"
          - "http://cms-monitoring.cern.ch:30093"
          - "60"
          - "1"
          image: cmssw/cmsmon-alerts:20200601-v1
          name: alerts
          volumeMounts:
          - name: alerts-secrets
            mountPath: /etc/cmsmon-alerts
            readOnly: true
        volumes:
        - name: alerts-secrets
          secret:
            secretName: alerts-secrets
