apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggus-alerts
  namespace: alerts
  labels:
     app: ggus-alerts
spec:
   replicas: 1
   selector:
     matchLabels:
       app: ggus-alerts
   template:
      metadata:
         labels:
           app: ggus-alerts
      spec:
        containers:
        - args:
          - /data/ggus_alert.sh
          - "xml"
          - "/data/data.json"
          - "http://cms-monitoring-ha2.cern.ch:30093"
          - "60"
          - "cms"
          - "10"
          - "1"
          image: registry.cern.ch/cmsmonitoring/cmsmon-alerts:go-0.6.0
          name: alerts
          env:
            - name: X509_USER_PROXY
              value: "/etc/proxy/proxy"
          volumeMounts:
          - name: alerts-secrets
            mountPath: /etc/cmsmon-alerts
            readOnly: true
          - name: proxy-secrets
            mountPath: /etc/proxy
            readOnly: true
        volumes:
        - name: alerts-secrets
          secret:
            secretName: alerts-secrets
        - name: proxy-secrets
          secret:
            secretName: proxy-secrets
