kind: Service
apiVersion: v1
metadata:
  name: confdb
  namespace: confdb
spec:
  selector:
    app: confdb
  ports:
    - port: 8340
      targetPort: 8340
      name: confdb
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: confdb
  labels:
    app: confdb
  namespace: confdb
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _confdb
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: confdb
  name: confdb
  namespace: confdb
spec:
  selector:
    matchLabels:
      app: confdb
  replicas: 1 #PROD# 2
  template:
    metadata:
      labels:
        app: confdb
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18340"
    spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: registry.cern.ch/cmsweb/confdb #imagetag
        name: confdb
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8340
          protocol: TCP
          name: confdb
        - containerPort: 18340
          protocol: TCP
          name: confdb-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/confdb
        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: confdb-secrets
      - name: etc-grid-security
        hostPath:
          path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: confdb
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-confdb
