kind: Service
apiVersion: v1
metadata:
  name: crabserver
  namespace: crab
spec:
  selector:
    app: crabserver
  ports:
    - port: 8270
      targetPort: 8270
      name: crabserver
    - port: 18270
      targetPort: 18270
      name: crabserver-mon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: crabserver
  name: crabserver
  namespace: crab
spec:
  selector:
    matchLabels:
      app: crabserver
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: crabserver
    spec:
      containers:
      #- image: sbelforte/crabserver:3.3.1911.rc3
      - image: cmssw/crabserver
        name: crabserver
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8270
          protocol: TCP
          name: crabserver
        - containerPort: 18270
          protocol: TCP
          name: crabserver-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/crabserver
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: crabserver-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-crab
