---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crabserver-filebeat-config
  namespace: crab
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/crabserver/crabserver-*${MY_POD_NAME}*.log
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
      processors:
        - add_fields:
            target: logtype
            fields:
              name: cherrypylog
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/crabserver/CRAB-*${MY_POD_NAME}*.log
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
      processors:
        - add_fields:
            target: logtype
            fields:
              name: crablog
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME} Type=%{[logtype][name]}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crabserver-filebeat-monit-config
  namespace: crab
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/crabserver/crabserver-*${MY_POD_NAME}*.log
      file_identity.path:
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
      include_lines:
        - '^\[.+?\] crabserver-'
      tags: ["crabhttpcall"]
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/crabserver/CRAB-*${MY_POD_NAME}*.log
      file_identity.path:
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
      include_lines:
        - 'MeasureTime:seconds - '
        - 'MeasureSize:bytes - '
      tags: ["crabrest"]
    output.logstash:
      hosts: ["logstash:5044"]
      compression_level: 3
      bulk_max_size: 4096
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
---
kind: Service
apiVersion: v1
metadata:
  name: crabserver
  namespace: crab
spec:
  selector:
    app: crabserver
  ports:
    - port: 8270
      targetPort: 8270
      name: crabserver
    - port: 18270
      targetPort: 18270
      name: crabserver-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: crabserver
  labels:
    app: crabserver
  namespace: crab
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    sudo cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    #su  -c "cd /data && /data/run.sh" --preserve-environment  _crabserver
    cd /data && /data/run.sh
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: crabserver
  name: crabserver
  namespace: crab
spec:
  selector:
    matchLabels:
      app: crabserver
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: crabserver
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18270"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      #- image: sbelforte/crabserver:3.3.1911.rc3
      - image: registry.cern.ch/cmsweb/crabserver #imagetag
        name: crabserver
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              cmsweb-ping --url=http://localhost:8270/crabserver/prod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
          initialDelaySeconds: 120
          failureThreshold: 3
          periodSeconds: 60
          timeoutSeconds: 60
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              cmsweb-ping --url=http://localhost:8270/crabserver/prod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
          periodSeconds: 60
          timeoutSeconds: 60
        ports:
        - containerPort: 8270
          protocol: TCP
          name: crabserver
        - containerPort: 18270
          protocol: TCP
          name: crabserver-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: robot-secrets
          mountPath: /etc/robots
          readOnly: true
        - name: hmac-secrets
          mountPath: /etc/hmac
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
        - name: token-secrets
          mountPath: /etc/token
          readOnly: true
#PROD#  - name: logs
#PROD#    mountPath: /data/srv/logs/crabserver
        securityContext:
          privileged: true
#PROD#- name: crabserver-filebeat
#PROD#  image: docker.elastic.co/beats/filebeat:7.12.0
#PROD#  args: [
#PROD#    "-c", "/etc/filebeat.yml",
#PROD#    "-e",
#PROD#  ]
#PROD#  env:
#PROD#  - name: MY_POD_NAME
#PROD#    valueFrom:
#PROD#      fieldRef:
#PROD#        apiVersion: v1
#PROD#        fieldPath: metadata.name
#PROD#  resources:
#PROD#    requests:
#PROD#      memory: "50Mi"
#PROD#      cpu: "50m"
#PROD#  volumeMounts:
#PROD#  - name: logs
#PROD#    mountPath: /data/srv/logs/crabserver
#PROD#  - name: config
#PROD#    mountPath: /etc/filebeat.yml
#PROD#    readOnly: true
#PROD#    subPath: filebeat.yml
#PROD#  - name: data
#PROD#    mountPath: /usr/share/filebeat/data
#PROD#  - name: varlog
#PROD#    mountPath: /var/log
#PROD#  - name: varlibdockercontainers
#PROD#    mountPath: /var/lib/docker/containers
#PROD#    readOnly: true
#PROD#  securityContext:
#PROD#    allowPrivilegeEscalation: false
#PROD#- name: crabserver-filebeat-monit
#PROD#  image: docker.elastic.co/beats/filebeat:8.1.3
#PROD#  args: [
#PROD#    "bash",
#PROD#    "-c",
#PROD#    "filebeat -c /etc/filebeat.yml --path.data /data/filebeat/${MY_POD_NAME}/data -e",
#PROD#  ]
#PROD#  env:
#PROD#  - name: MY_POD_NAME
#PROD#    valueFrom:
#PROD#      fieldRef:
#PROD#        apiVersion: v1
#PROD#        fieldPath: metadata.name
#PROD#  resources:
#PROD#    requests:
#PROD#      memory: "150Mi"
#PROD#      cpu: "50m"
#PROD#    limits:
#PROD#      memory: "1Gi"
#PROD#      cpu: "500m"
#PROD#  volumeMounts:
#PROD#  - name: logs
#PROD#    mountPath: /data/srv/logs/crabserver
#PROD#  - name: crabserver-filebeat-monit-config
#PROD#    mountPath: /etc/filebeat.yml
#PROD#    readOnly: true
#PROD#    subPath: filebeat.yml
#PROD#  - name: filebeat-cephfs
#PROD#    mountPath: /data/filebeat
#PROD#  securityContext:
#PROD#    allowPrivilegeEscalation: false
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: crabserver-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: crabserver
      - name: token-secrets
        secret:
          secretName: token-secrets
#PROD#- name: logs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-crab
#PROD#- name: varlog
#PROD#  hostPath:
#PROD#    path: /var/log
#PROD#- name: varlibdockercontainers
#PROD#  hostPath:
#PROD#    path: /var/lib/docker/containers
#PROD#- name: config
#PROD#  configMap:
#PROD#    defaultMode: 0640
#PROD#    name: crabserver-filebeat-config
#PROD#- name: data
#PROD#  emptyDir: {}
#PROD#- name: crabserver-filebeat-monit-config
#PROD#  configMap:
#PROD#    defaultMode: 0640
#PROD#    name: crabserver-filebeat-monit-config
#PROD#- name: filebeat-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: crabserver-filebeat-monit-data
