kind: Service
apiVersion: v1
metadata:
  name: dbs-global-w
  namespace: dbs
spec:
  selector:
    app: dbs-global-w
  ports:
    - port: 8253
      targetPort: 8253
      name: dbs-global-w
    - port: 18253
      targetPort: 18253
      name: dbs-gw-mon
    - port: 19253
      targetPort: 19253
      name: dbs-gw-cpy-mon
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: dbs-global-w
  name: dbs-global-w
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbs-global-w
  replicas: 1 #PROD# 4
  template:
    metadata:
      labels:
        app: dbs-global-w
    spec:
      containers:
      - image: cmssw/dbs
        name: dbs-global-w
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "10Gi"
            cpu: "800m"
        ports:
        - containerPort: 8253
          protocol: TCP
          name: dbs-global-w
        - containerPort: 18253
          protocol: TCP
          name: dbs-gw-mon
        - containerPort: 19253
          protocol: TCP
          name: dbs-gw-cpy-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          defaultMode: 256
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/dbs
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbs-global-w-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim
