kind: Service
apiVersion: v1
metadata:
  name: dbs-migrate
  namespace: dbs
spec:
  selector:
    app: dbs-migrate
  ports:
    - port: 8257
      targetPort: 8257
      name: dbs-migrate
    - port: 18257
      targetPort: 18257
      name: dbs-mig-mon
    - port: 19257
      targetPort: 19257
      name: dbs-mig-cpy-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbs-migrate
  labels:
    app: dbs-migrate
  namespace: dbs
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _dbs
---    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbs-migrate
  name: dbs-migrate
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbs-migrate
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: dbs-migrate
        env: k8s #k8s#
        job: dbs-migrate
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18257"
#         prometheus.io/port: "19257"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/dbs #imagetag
        name: dbs-migrate
        livenessProbe:
          exec:
            command:
            - cmsweb-ping
            - "--url=http://localhost:8257/dbs/prod/global/DBSMigrate/"
            - "--authz=/etc/secrets/hmac"
            - -verbose
            - "0"
          initialDelaySeconds: 100
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "10Gi"
            cpu: "800m"
        ports:
        - containerPort: 8257
          protocol: TCP
          name: dbs-migrate
        - containerPort: 18257
          protocol: TCP
          name: dbs-mig-mon
        - containerPort: 19257
          protocol: TCP
          name: dbs-mig-cpy-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/dbs
        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbs-migrate-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dbs-migrate
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dbs
