kind: Service
apiVersion: v1
metadata:
  name: exitcodes
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 9201
    protocol: TCP
    name: http
  selector:
    app: exitcodes
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: exitcodes
  name: exitcodes
  namespace: http
spec:
  selector:
    matchLabels:
      app: exitcodes
  replicas: 1
  template:
    metadata:
      labels:
        app: exitcodes
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: cmssw/exitcodes #imagetag
        name: exitcodes
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 9201
