apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbs-phys03-w.fullname" . }}
  labels:
    {{- include "dbs-phys03-w.labels" . | nindent 4 }}
  namespace: dbs
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- if or .Values.environment.prod .Values.environment.preprod}}
  replicas: {{ .Values.replicaCount.prod }}
  {{- else }}
  replicas: {{ .Values.replicaCount.test }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dbs-phys03-w.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dbs-phys03-w.selectorLabels" . | nindent 8 }}
        {{- if .Values.environment.preprod}}
        env: k8s-preprod
        {{- end }}
        {{- if .Values.environment.prod}}
        env: k8s-prod
        {{- end }}
        {{- if .Values.environment.test}}
        env: k8s
        {{- end }}
        job: dbs-phys03-w
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dbs-phys03-w.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
           - containerPort: {{ .Values.service.port }}
             name: {{ .Values.service.name }}
             protocol: {{ .Values.service.protocol }}
           - containerPort: {{ .Values.serviceMon.port }}
             name: {{ .Values.serviceMon.name }}
             protocol: {{ .Values.serviceMon.protocol }}
           - containerPort: {{ .Values.serviceCpyMon.port }}
             name: {{ .Values.serviceCpyMon.name }}
             protocol: {{ .Values.serviceCpyMon.protocol }}
          command:
           {{- toYaml .Values.image.command | nindent 10 }}
          livenessProbe:
          {{- if .Values.environment.prod}}
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.livenessProbePreProd | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: proxy-secrets
            mountPath: /etc/proxy
            readOnly: true
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
          - name: robot-secrets
            mountPath: /etc/robots
            readOnly: true
          - name: hmac-secrets
            mountPath: /etc/hmac
            readOnly: true
          - mountPath: /host/etc/grid-security
            name: etc-grid-security
            readOnly: true
          - name: setup-certs-and-run
            mountPath: /opt/setup-certs-and-run
{{- if or .Values.environment.prod .Values.environment.preprod }}
          - name: logs
            mountPath: /data/srv/logs/dbs
        - name: {{ .Values.imageFilebeat.name }}
          image: {{ .Values.imageFilebeat.path }}
          env:
          {{- toYaml .Values.imageFilebeat.env | nindent 10 }}
          args:
          {{- toYaml .Values.imageFilebeat.args | nindent 10 }}
          resources:
          {{- toYaml .Values.imageFilebeatResources | nindent 12 }}
          volumeMounts:
          - name: logs
            mountPath: /data/srv/logs/dbs
          - name: config
            mountPath: /etc/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          - name: data
            mountPath: /usr/share/filebeat/data
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          securityContext:
          {{- toYaml .Values.imageFilebeatSecurityContext | nindent 12 }}
{{- end }}
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbs-phys03-w-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dbs-phys03-w
{{- if or .Values.environment.prod .Values.environment.preprod }}
      - name: logs
        persistentVolumeClaim:
{{- if .Values.environment.preprod }}
            claimName: logs-cephfs-claim-preprod-dbs
{{- end }}
{{- if .Values.environment.prod }}
            claimName: logs-cephfs-claim-prod-dbs
{{- end }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          defaultMode: 0640
          name: dbs-phys03-w-filebeat-config
      - name: data
        emptyDir: {}
{{- end }}
