image:
  repository: cmssw/rucio-probes

config:
  nagios:
    fts_vo: "cms"
    update_distances: "False"
  monitor:
    prometheus_servers: "prometheus-pushgateway:9091"
    prometheus_prefix: "rucio_"

probes:
  check_fts_backlog:
    interval: 1
  check_messages_to_submit:
    interval: 1
  check_oracle:
    interval: 1
  check_requests_to_rses:
    interval: 1
  check_stuck_rules:
    interval: 1
  check_transfer_queues_status:
    interval: 1
  check_unevaluated_dids:
    interval: 1
  check_unlocked_replicas:
    interval: 1
  check_expired_dids:
    interval: 1
  check_new_dids:
    interval: 1
  check_updated_dids:
    interval: 1
  check_expected_total_number_of_files_per_rse:
    interval: 1
  check_not_OK_rules_per_rse:
    interval: 1
  check_number_of_missing_files_per_rse:
    interval: 1
  check_obsolete_replicas:
    interval: 10
  check_deletable_replicas:
    interval: 10
  check_report_free_space:
    interval: 120
  check_report_used_space:
    interval: 120
  check_rules_with_0_completion_volume:
    interval: 1
  check_expiring_rules_per_rse:
    interval: 1
  check_missing_data_at_rse:
    interval: 1
  check_unlocked_replicas_per_rse:
    interval: 1
  check_space_uniquely_used_by_rucio:
    interval: 30
  check_expired_locked_rules:
    interval: 1

voProbes: 
  check_rule_counts:
    interval: 30
    voName: cms


