image:
  repository: cmssw/rucio-server

# For NGINX ingress. Eventually becomes plain server

replicaCount: 1
authReplicaCount: 1
traceReplicaCount: 1

# Use http worker mode and elsewhere configure database connections for Oracle Database Resident Connection Pool (DRCP)

httpd_config:
  encoded_slashes: "True"
#  mpm_mode: "worker"
#  start_servers: "1"
#  min_spare_threads: "1"
#  max_spare_threads: "20"
#  threads_per_child: "5"
#  max_clients: "20"
#  max_requests_per_child: "8192"

# The server runs on port 80 and there is no need for SSL passthrough

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http, https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - cms-rucio-dev.cern.ch
  tls: 
    - secretName: rucio-server.tls-secret

# Auth server runs on 443 and needs the connection forwarded straight through

useSSL:
  authServer: true

authService:
  type: ClusterIP
  port: 443
  targetPort: https
  protocol: TCP
  name: https
  annotations: {}

authServer:
  useSSL: true
  servicePort: 443
  targetPort: https
  portName: https

authIngress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts: 
    - cms-rucio-auth-dev.cern.ch

traceIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http, https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /


serverResources:
  requests:
    memory: 500Mi
  limits:
    memory: 1500Mi

authServerResources:
  requests:
    memory: 500Mi
  limits:
    memory: 800Mi

traceServerResources:
  requests:
    memory: 400Mi
  limits:
    memory: 600Mi

config:
  common:
      loglevel: "INFO"
  trace:
      port: "61313"
      brokers: "cms-mb.cern.ch"
      topic: "/topic/cms.rucio.tracer"
      username: "cmsrucio"
      #config.trace.tracedir: directory where traces are written to (default "/var/log/rucio/trace")
      tracedir: "/var/log/rucio/trace"

