image:
  tag: release-1.19.5

config:
    accounts:
        special_accounts: "tier0"
    policy:
        permission: "cms"
        schema: "cms"
        lfn2pfn_algorithm_default: "identity"
        lfn2pfn_module: "cmstfc"
        support: "https://its.cern.ch/jira/projects/CMSRUCIO/summary"
    messaging_hermes:
        brokers: "localhost"
        voname: "cms"    
        email_from: "cms-rucio-dev@cern.ch"
    messaging_cache:
        brokers: "localhost"
        voname: "cms"    
    messaging_fts3:
        brokers: "localhost"
        voname: "cms"    
    tracer_kronos:
        brokers: "localhost"
        voname: "cms"    
    conveyor:
        ftshosts: "https://cmsfts3.fnal.gov:8446,https://fts3.cern.ch:8446,https://lcgfts3.gridpp.rl.ac.uk:8446"
    monitor:
        carbon_server: statsd-exporter-rucio-statsd-exporter
        user_scope: rucio

# Configure database connections for Oracle Database Resident Connection Pool (DRCP)

    database:
      pool_reset_on_return: "rollback"
      pool_timeout: "30"
      echo: "0"
      max_overflow: "10"
      pool_size: "2"
      pool_recycle: "600"
