apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-config
data:
  site-sync.yaml: |+
    # Main configuration
    main:
        pool: 3
        sleep: 60
        verbosity: SUMMARY
        run:
          "for:13000"   # True YAML does not work
    default:
        pool: 1
        chunck: 100000
        #select: /AOD
    T0_CH_CERN_Tape:
        pool: 5
        multi_das_calls: True
    T1_DE_KIT_Tape:
        pool: 5
        multi_das_calls: True
    T1_ES_PIC_Tape:
        pool: 5
        multi_das_calls: True
    T1_FR_CCIN2P3_Tape:
        pool: 5
        multi_das_calls: True
    T1_IT_CNAF_Tape:
        pool: 5
        multi_das_calls: True
    T1_RU_JINR_Tape:
        pool: 5
        multi_das_calls: True
    T1_UK_RAL_Tape:
        pool: 5
        multi_das_calls: True
    T1_US_FNAL_Tape:
        pool: 5
        multi_das_calls: True
    T1_DE_KIT_Disk:
        pool: 5
        multi_das_calls: True
    T1_ES_PIC_Disk:
        pool: 5
        multi_das_calls: True
    T1_FR_CCIN2P3_Disk:
        pool: 5
        multi_das_calls: True
    T1_UK_RAL_Disk:
        pool: 5
        multi_das_calls: True
    T1_US_FNAL_Disk:
        pool: 5
        multi_das_calls: True
    T2_AT_Vienna:
        select:
          - '\S+NANOAOD\S+'
    T2_BE_IIHE:
        multi_das_calls: True
    T2_BE_UCL:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_BR_SPRACE:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_BR_UERJ:
        select:
          - '\S+NANOAOD\S+'
    T2_CH_CSCS:
        select:
          - '\S+NANOAOD\S+'
    T2_CN_Beijing:
        select:
          - '\S+NANOAOD\S+'
    T2_DE_DESY:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_DE_RWTH:
        select:
          - '\S+NANOAOD\S+'
    T2_EE_Estonia:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_ES_CIEMAT:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_ES_IFCA:
        select:
          - '\S+NANOAOD\S+'
    T2_FI_HIP:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_FR_CCIN2P3:
        select:
          - '\S+NANOAOD\S+'
    T2_FR_GRIF_LLR:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_FR_GRIF_IRFU:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_FR_IPHC:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_GR_Ioannina:
        select:
          - '\S+NANOAOD\S+'
    T2_HU_Budapest:
        select:
          - '\S+NANOAOD\S+'
    T2_IN_TIFR:
        select:
          - '\S+NANOAOD\S+'
    T2_IT_Bari:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_IT_Legnaro:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_IT_Pisa:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_IT_Rome:
        select:
          - '\S+NANOAOD\S+'
    T2_KR_KISTI:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_KR_KNU:
        select:
          - '\S+NANOAOD\S+'
    T2_PK_NCP:
        select:
          - '\S+NANOAOD\S+'
    T2_PL_Swierk:
        select:
          - '\S+NANOAOD\S+'
    T2_PL_Warsaw:
        select:
          - '\S+NANOAOD\S+'
    T2_PT_NCG_Lisbon:
        select:
          - '\S+NANOAOD\S+'
    T2_RU_IHEP:
        select:
          - '\S+NANOAOD\S+'
    T2_RU_INR:
        select:
          - '\S+NANOAOD\S+'
    T2_RU_ITEP:
        multi_das_calls: True
    T2_RU_JINR:
        select:
          - '\S+NANOAOD\S+'
    T2_TR_METU:
        select:
          - '\S+NANOAOD\S+'
    T2_TW_NCHC:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_UA_KIPT:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_UK_London_Brunel:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_UK_London_IC:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_UK_SGrid_RALPP:
        multi_das_calls: True
        select:
          - '\S+NANOAOD\S+'
    T2_UK_SGrid_Bristol:
        select:
          - '\S+NANOAOD\S+'
    T2_US_Nebraska:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_UCSD:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_Florida:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_Caltech:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_MIT:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_Purdue:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_Vanderbilt:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T2_US_Wisconsin:
        multi_das_calls: True         
        select:
          - '\S+NANOAOD\S+'
    T3_FR_IPNL:
        select:
          - '\S+NANOAOD\S+'
    T3_US_NotreDame:
        select:
          - '\S+NANOAOD\S+'
    T3_CH_CERN_OpenData:
        select:
          - '\S+NANOAOD\S+'
    T3_IT_Trieste:
        select:
          - '\S+NANOAOD\S+'
    T3_KR_KISTI:
        select:
          - '\S+NANOAOD\S+'
    T3_US_Baylor:
        select:
          - '\S+NANOAOD\S+'
    T3_US_Colorado:
        select:
          - '\S+NANOAOD\S+'
    T3_US_FNALLPC:
        select:
          - '\S+NANOAOD\S+'
    T3_US_MIT:
        select:
          - '\S+NANOAOD\S+'
    T3_US_Princeton_ICSE:
        select:
          - '\S+NANOAOD\S+'
    T3_US_Rutgers:
        select:
          - '\S+NANOAOD\S+'
    T3_US_UMD:
        select:
          - '\S+NANOAOD\S+'
    T3_US_UMiss:
        select:
          - '\S+NANOAOD\S+'
    T3_CH_PSI:
        select:
          - '\S+NANOAOD\S+'  
    T3_TW_NTU_HEP:
        select:
          - '\S+NANOAOD\S+'  
    T3_US_Brown:
        select:
          - '\S+NANOAOD\S+'  
    T3_US_TAMU:
        select:
          - '\S+NANOAOD\S+'  
    T3_KR_UOS:
        select:
          - '\S+NANOAOD\S+'  

