# Main configuration
main:
# Number of sites to be synched in parallel
    pool: 2
#
# Sleep between polling (default )
    sleep: 60
#
# Verbosity. Default is SUMMARY
    verbosity: VNOTICE
#
# run status: 
# True: run (default), 
# False: drain and stop,
# until:YYYY-MM-DD:HH:mm:SS run until date
# for:NN run for NN seconds
    run: 
      "for:1800"   # True YAML does not work


# Default site conf can be overwritten by site specific
# sections
default:
# Number of blocks to the synched in parallel
    pool: 1
# 
#
# run status: 
# True: run (default), 
# False: drain and stop,
# since:YYYY-MM-DD:HH:mm:SS start running at date (assuming the service is running)
# until:YYYY-MM-DD:HH:mm:SS run until date
# for:NN run for NN seconds
#
#   run: True
#
#
# Number of blocks to be considered at each iteration
    chunck: 1000
#
#
# Run in dry mode (default False)
#    dry: True
#
#
# Verbosity level for the site thread (default SUMMARY) uncomment to have more
#    verbosity: VNOTICE
#
# Verbosity level for the block threads (default SUMMARY) uncomment to have more
#    block_verbosity: VNOTICE
#
# Make a das call for each group of dataset with the same first letter
# This is an ugly workaround to avoid making a giant das call with all the blocks
# at a big site.
#    multi_das_calls: False


# List of sites
T2_FR_GRIF_LLR:
    pool: 1

T2_FR_GRIF_IRFU:
    pool: 1

T2_FR_IPHC:
    pool: 1

T2_FR_CCIN2P3:
    pool: 1

T3_FR_IPNL:
    pool: 1

#T1_FR_CCIN2P3_Buffer:
#    chunck: 3000
#    pool: 1
#    multi_das_calls: True
#    ignore:
#        - '\S+/Commissioning09\S+'
#        - '\S+/CRUZET\S+'
#        - '\S+/Commissioning08\S+'
#        - '\S+/CRAFT09\S+'
#        - '\S+/BeamCommissioning09\S+'
#        - '\S+/BeamCommissioning08\S+'
#    run: False

T2_IT_Pisa:
    pool: 1
        

T2_IT_Bari:
    pool: 1

T2_IT_Legnaro:
    pool: 1

T2_IT_Rome:
    pool: 1

T1_IT_CNAF_Disk:
    chunck: 3000
    pool: 5
    multi_das_calls: True
    ignore:
        - '\S+/Commissioning09\S+'
        - '\S+/CRUZET\S+'
        - '\S+/Commissioning08\S+'
        - '\S+/CRAFT09\S+'
        - '\S+/BeamCommissioning09\S+'
        - '\S+/BeamCommissioning08\S+'
    run: True

#T1_UK_RAL_Disk:
#    pool: 10


T2_DE_DESY:
    pool: 1

T2_DE_RWTH:
    pool: 1

